# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-31 08:34
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=255)),
                ('thumbnail_name', models.CharField(blank=True, max_length=255, null=True)),
                ('film_name', models.CharField(blank=True, max_length=255, null=True)),
                ('realisation', models.CharField(blank=True, max_length=255, null=True)),
                ('production', models.CharField(blank=True, max_length=255, null=True)),
                ('photo_direction', models.CharField(blank=True, max_length=255, null=True)),
                ('lto_archive_number', models.CharField(blank=True, max_length=255, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('additional_infos', jsonfield.fields.JSONField(default={})),
            ],
        ),
    ]
